name: deepl-cli(macos)

on:
  push:
    branches:
      - main
    paths:
      - 'Formula/deepl-cli.rb'
      - '.github/workflows/deepl-cli.yml'
  schedule:
    - cron: '51 3 * * 6'  # Runs at 03:51, only on Saturday
  workflow_dispatch:

jobs:
  test_installation:
    name: macos
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install (macos)
        run: |
          brew install kojix2/brew/deepl-cli
          run: deepl --version
