name: deepl-cli (macos) # edit

on:
  push:
    branches:
      - main
    paths:
      - "Formula/deepl-cli.rb" # edit
      - ".github/workflows/deepl-cli-macos.yml" # edit
  schedule:
    - cron: "51 3 * * 6" # Runs at 03:51, only on Saturday
  workflow_dispatch:

jobs:
  test_installation:
    name: macos
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install (macos)
        run: |
          brew install kojix2/brew/deepl-cli    # edit
          deepl --version                       # edit
